{{ config(materialized='table') }}

select
  -- keys
  {{ dbt_utils.generate_surrogate_key(['id']) }} as website_sk,
  id as website_nk,

  -- attributes (subset of requested fields with sensible defaults)
  id,
  name,
  domain,
  vendor_id,
  created_at,
  updated_at,
  parent_id,
  sms_from,
  email_from,
  `index`,
  `version`,
  coalesce(cast(bonus as numeric), 0.02) as bonus,
  coalesce(cancel_hour, 48) as cancel_hour,
  category_header,
  coalesce(is_active, true) as is_active,
  coalesce(`group`, false) as is_group,
  coalesce(wallet, false) as wallet,
  coalesce(coupon, false) as coupon,
  coalesce(gift_card, false) as gift_card,
  coalesce(ticket, false) as ticket,
  phone1,
  phone2,
  email,
  address,
  copyright_text,
  white_content_type,
  search_suggestion,
  coalesce(candy, false) as candy,
  coalesce(leasing, false) as leasing,
  alternate_domain,
  lease_account,
  lease_name,
  currency,
  payment_guide_text,
  ebarimt,
  payment_account_data,
  commission,
  min_cart_amount,
  auto_ebarimt,
  listing_bonus,
  show_user,
  auto_accept_merchants,
  auto_accept_business_clients,
  delivery_until,
  vat_register,
  vat_secret,
  vat_group,
  use_custom_prototypes,
  use_wallet,
  shipment_hours,
  vat_district,
  use_alternate_password,
  order_cancellation_fee,
  order_cancellation_base,
  use_delivery_code,
  coalesce(sms_fee, 55) as sms_fee,
  preferences,
  sms_delay
from {{ source('shoppy_aurora', 'raw_shoppy_websites') }}

